<?php

namespace AppBundle\Repository;

/**
 * ProbleemStellingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProbleemStellingRepository extends \Doctrine\ORM\EntityRepository
{
}
