<?php

namespace AppBundle\Repository;

/**
 * StatusMeldingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusMeldingRepository extends \Doctrine\ORM\EntityRepository
{
}
