<?php

namespace AppBundle\Repository;

/**
 * TechnicusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TechnicusRepository extends \Doctrine\ORM\EntityRepository
{
}
